// Builds the Zenith design tokens (single source of truth) into:
//   build/tokens.css           — CSS custom properties (light + dark + auto-dark)
//   build/tokens.studio.json   — Tokens Studio file for Figma import
//   build/tokens.{light,dark}.json — resolved token trees
// and copies tokens.css into the component library at
//   ../zenith-ui/src/tokens.generated.css
import StyleDictionary from "style-dictionary";
import { outputReferencesFilter } from "style-dictionary/utils";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";

const TMP = "build/.tmp";

// CSS variable names: drop the "semantic" group prefix, keep everything else,
// and prefix with "zen". e.g. semantic.surface-2 -> --zen-surface-2,
// radius.m -> --zen-radius-m, font -> --zen-font.
StyleDictionary.registerTransform({
  name: "name/zen-css",
  type: "name",
  transform: (token) => {
    const path = token.path[0] === "semantic" ? token.path.slice(1) : token.path;
    return "zen-" + path.join("-");
  },
});

const TRANSFORMS = ["attribute/cti", "name/zen-css", "color/css"];

function sourcesFor(mode) {
  return ["tokens/base.json", `tokens/color.${mode}.json`, `tokens/semantic.${mode}.json`];
}

async function buildCss(mode, selector, onlySemantic) {
  const dest = `${mode}-${onlySemantic ? "sem" : "all"}.css`;
  const sd = new StyleDictionary({
    usesDtcg: true,
    log: { verbosity: "silent" },
    source: sourcesFor(mode),
    platforms: {
      css: {
        transforms: TRANSFORMS,
        buildPath: `${TMP}/`,
        files: [
          {
            destination: dest,
            format: "css/variables",
            // CSS exposes semantic tokens (+ base in light); primitives stay in
            // the Figma/JSON outputs only.
            filter: (t) =>
              onlySemantic ? t.path[0] === "semantic" : t.path[0] !== "color",
            options: {
              selector,
              showFileHeader: false,
              outputReferences: outputReferencesFilter,
            },
          },
        ],
      },
    },
  });
  await sd.buildAllPlatforms();
  return (await fs.readFile(`${TMP}/${dest}`, "utf8")).trim();
}

async function buildJson(mode) {
  const sd = new StyleDictionary({
    usesDtcg: true,
    log: { verbosity: "silent" },
    source: sourcesFor(mode),
    platforms: {
      json: {
        transformGroup: "js",
        buildPath: "build/",
        files: [{ destination: `tokens.${mode}.json`, format: "json/nested" }],
      },
    },
  });
  await sd.buildAllPlatforms();
}

async function buildStudio() {
  const read = async (f) => JSON.parse(await fs.readFile(`tokens/${f}`, "utf8"));
  const [base, cl, sl, cd, sd] = await Promise.all([
    read("base.json"),
    read("color.light.json"),
    read("semantic.light.json"),
    read("color.dark.json"),
    read("semantic.dark.json"),
  ]);
  const studio = {
    global: base,
    light: { ...cl, ...sl },
    dark: { ...cd, ...sd },
    $themes: [
      { id: "light", name: "Light", selectedTokenSets: { global: "source", light: "enabled" } },
      { id: "dark", name: "Dark", selectedTokenSets: { global: "source", dark: "enabled" } },
    ],
    $metadata: { tokenSetOrder: ["global", "light", "dark"] },
  };
  await fs.writeFile("build/tokens.studio.json", JSON.stringify(studio, null, 2) + "\n");
}

async function main() {
  await fs.mkdir("build", { recursive: true });

  const light = await buildCss("light", ":root", false);
  const dark = await buildCss("dark", ':root[data-theme="dark"], .zen-dark', true);
  const darkAuto = await buildCss(
    "dark",
    ':root:not([data-theme="light"]):not([data-theme="dark"])',
    true
  );
  const indented = darkAuto
    .split("\n")
    .map((l) => (l.trim() ? "  " + l : l))
    .join("\n");

  const css = [
    "/* AUTO-GENERATED by @zenith-ui/tokens — do not edit by hand. */",
    "/* Source: packages/tokens/tokens/*.json  ·  Rebuild: npm run build -w @zenith-ui/tokens */",
    "",
    light,
    "",
    dark,
    "",
    "/* Auto dark when the app has not pinned a theme */",
    "@media (prefers-color-scheme: dark) {",
    indented,
    "}",
    "",
  ].join("\n");

  await fs.writeFile("build/tokens.css", css);
  await fs.copyFile("build/tokens.css", "../zenith-ui/src/tokens.generated.css");

  await buildJson("light");
  await buildJson("dark");
  await buildStudio();

  // Convenience: also drop the Figma import file into ~/Downloads if it exists.
  let copiedToDownloads = false;
  try {
    const downloads = path.join(os.homedir(), "Downloads");
    await fs.access(downloads);
    await fs.copyFile("build/tokens.studio.json", path.join(downloads, "tokens.studio.json"));
    copiedToDownloads = true;
  } catch {
    /* no Downloads folder — skip */
  }

  await fs.rm(TMP, { recursive: true, force: true });
  console.log(
    "✓ tokens built → build/tokens.css, tokens.studio.json, tokens.{light,dark}.json (and copied into the library)"
  );
  if (copiedToDownloads) {
    console.log("  → tokens.studio.json also copied to ~/Downloads for Figma import");
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
